template = ShipTemplate():setName("Wrecked Destroyer"):setClass("Escort", "Destroyer"):setModel("cobraDestroyer")
template:setDescription([[The wreck of a once-proud Cobra Destroyer, now darkened forever in the void of the Wake.]])
template:setRadarTrace("radar_cobra.png")
template:setHull(140)
template:setSpeed(0, 0, 0)

template = ShipTemplate():setName("Wrecked Frigate"):setClass("Escort", "Frigate"):setModel("swordClassFrigate")
template:setDescription([[The wreck of a once-proud Sword Frigate, now darkened forever in the void of the Wake.]])
template:setRadarTrace("radar_sword.png")
template:setHull(200)
template:setSpeed(0, 0, 0)

template = ShipTemplate():setName("Wrecked Cruiser"):setClass("Ship of the Line", "Cruiser"):setModel("lunarClassCruiser")
template:setDescription([[The wreck of a once-proud Lunar Cruiser, now darkened forever in the void of the Wake.]])
template:setRadarTrace("radar_lunar.png")
template:setHull(300)
template:setSpeed(0, 0, 0)

template = ShipTemplate():setName("Wrecked Battleship"):setClass("Battleship", "Emperor"):setModel("emperorClassBattleship")
template:setDescription([[The wreck of a once-proud Emperor-class battleship, now darkened forever in the void of the Wake.]])
template:setRadarTrace("radar_emperor.png")
template:setHull(800)
template:setSpeed(0, 0, 0)

template = ShipTemplate():setName("Wrecked Light Freighter"):setClass("Freighter", "Light"):setModel("lightFreighter")
template:setDescription([[The wreck of a light Imperial Freighter, now darkened forever in the void of the Wake.]])
template:setRadarTrace("radar_light_freighter.png")
template:setHull(70)
template:setSpeed(0, 0, 0)

template = ShipTemplate():setName("Wrecked Freighter"):setClass("Freighter", "Medium"):setModel("mediumFreighter")
template:setDescription([[The wreck of an Imperial Freighter, now darkened forever in the void of the Wake.]])
template:setRadarTrace("radar_medium_freighter.png")
template:setHull(140)
template:setSpeed(0, 0, 0)

template = ShipTemplate():setName("Wrecked Bulk Carrier"):setClass("Freighter", "Heavy"):setModel("heavyFreighter")
template:setDescription([[The wreck of an Imperial Bulk Freighter, now darkened forever in the void of the Wake.]])
template:setRadarTrace("radar_heavy_freighter.png")
template:setHull(500)
template:setSpeed(0, 0, 0)

template = ShipTemplate():setName("General Wreckage"):setClass("Wreckage", "Wreckage"):setModel("mediumFreighter")
template:setDescription([[Wreckage]])
template:setRadarTrace("radar_medium_freighter.png")
template:setHull(500)
template:setSpeed(0, 0, 0)