template = ShipTemplate():setName("Tug Ship"):setClass("Utility", "Tug"):setModel("lightFreighter")
template:setRadarTrace("radar_light_freighter.png")
template:setDescription([[Terrier class]])
template:setHull(30)
template:setShields(0)
template:setSpeed(30, 10, 1)
template:setDefaultAI('fighter')
